version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - appNetwork

  web:
    build: ./web
    restart: always
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/web
    networks:
      - appNetwork

volumes:
  db:
    driver: local

networks:
  appNetwork:
    driver: bridge
