version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/minf-commerce/data
    networks:
      - appNetwork

  web:
    build: ./apps/web
    depends_on:
      - db
    restart: always
    env_file:
      - ./apps/web/.env
    ports:
      - "4000:3000"
    networks:
      - appNetwork

volumes:
  db:
    driver: local

networks:
  appNetwork:
    driver: bridge
