version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/minf-commerce/data
    networks:
      - webNetwork
      - baselinkerApiNetwork

  # web:
  #   build: ./apps/web
  #   depends_on:
  #     - db
  #   restart: always
  #   env_file:
  #     - ./apps/web/.env
  #   ports:
  #     - "4000:3000"
  #   networks:
  #     - webNetwork

  baselinker-api:
    build:
      args:
        - APP=baselinker-api
        - START_COMMAND=dev
      context: .
      dockerfile: ./apps/baselinker-api/Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
      - BASELINKER_PASSWORD=
    ports:
      - "4040:4040"
    networks:
      - baselinkerApiNetwork

volumes:
  db:
    driver: local

networks:
  webNetwork:
    driver: bridge
  baselinkerApiNetwork:
    driver: bridge
