import "./globals.css";
import { Inter } from "next/font/google";
import { Hydrate, dehydrate } from "@tanstack/react-query";
import { Providers } from "@modules/providers";
import { ContentContainer, Footer, Navbar } from "@modules/layout";
import {
  fetchCategories,
  getQueryClient,
  useCategoriesQueryKey,
} from "@modules/api/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MinfCommerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = getQueryClient();
  await queryClient.prefetchQuery([useCategoriesQueryKey], fetchCategories);
  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Hydrate state={dehydratedState}>
            <Navbar />
            <ContentContainer>
              <main>{children}</main>
            </ContentContainer>
            <Footer />
          </Hydrate>
        </Providers>
      </body>
    </html>
  );
}
