name: Deploy to Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: johndoems/prezentydlaciebie:latest

      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_SSH_HOST }}
      #     username: dev
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker pull johndoems/prezentydlaciebie:latest
      #       docker-compose down || true
      #       docker-compose up -d
