name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web
          push: true
          tags: johndoems/prezentydlaciebie:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: dev
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          # key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull johndoems/prezentydlaciebie:latest
            cd /home/dev/apps/minf-commerce/runner/minf-commerce/minf-commerce
            docker-compose down || true
            docker-compose -f docker-compose.yaml up -d
